FROM ghcr.io/astral-sh/uv:python3.13-bookworm-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /reddit-meter-api

# Install only necessary runtime dependencies
RUN uv pip install --system \
    fastapi[all] \
    uvicorn \
    python-dotenv \
    google-cloud-firestore

# Copy only your API code
COPY app/api ./app/api
COPY app/storage ./app/storage
COPY Makefile ./

CMD ["uv", "run", "uvicorn", "app.api.main:app", "--host", "0.0.0.0", "--port", "8080"]
